## Numpy array and basics
learn about numpy with ashu

In [4]:
import numpy as np                                                                                                              

In [5]:
arr = np.array([1,2,4,5,6])
print("1D array is :" , arr)

1D array is : [1 2 4 5 6]


In [7]:
arr = np.array([[1,3,4] , [2,4,5]])
print("2D array: ", arr)

2D array:  [[1 3 4]
 [2 4 5]]


List vs numpy array

In [2]:
import time
start = time.time()
py_List = [i*2 for i in range(1000000)]
print("\n List operate time", time.time() - start)


 List operate time 0.04784345626831055


In [5]:
start = time.time()
np_array = np.arange(1000000)*2
print("\n array operate time", time.time() - start)


 array operate time 0.00822591781616211


## creating array from scrach


In [7]:
zero = np.zeros((3,4))
print("zeros array: \n" ,zero)

ones = np.ones((2,3))
print("one array: \n", ones)

full  = np.full((2,2) ,7)
print("full array: \n", full)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]


In [8]:
random = np.random.random((2,3))
print("random array: \n",random)

random array: 
 [[0.09056056 0.58120352 0.69026366]
 [0.80992788 0.59829032 0.44086839]]


In [9]:
sequence = np.arange(0 , 10 ,2)
print("random array: \n" ,sequence)

random array: 
 [0 2 4 6 8]


## Vector Metrix and Tesnsor 


In [10]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3],
[4,5,6]])
print("Matrix:" ,matrix)

tensor = np.array([[[1,2], [3 ,4]],
[[5 ,6] ,[7,8]]])
print("tensor:" , tensor)

Vector:  [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties


In [11]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("Shape" , arr.shape)
print("Dimention" ,arr.ndim)
print("Size" , arr.size)
print("DType" ,arr.dtype)

Shape (2, 3)
Dimention 2
Size 6
DType int64


## Array Reshaping

In [14]:
arr = np.arange(12)
print("Original array", arr)

reshaped = arr.reshape((3 ,4))
print("\n reshapd array " , reshaped)

flattend = reshaped.flatten()
print("\n Flattend array ", flattend)

# ravel  { return view , insted of copy}
raveled = reshaped.ravel()
print("\n raveled array" ,raveled)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshapd array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# Transpose 
transpose = reshaped.T
print("\n transposed  array" ,transpose)


 transposed  array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
